# Generated by Django 6.0.5 on 2026-05-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('electrician', 'Electrician'), ('plumbing', 'Plumbing'), ('cleaning', 'Cleaning')], max_length=20)),
                ('tag', models.CharField(blank=True, choices=[('bestseller', 'Bestseller'), ('premium', 'Premium'), ('new', 'New'), ('popular', 'Popular'), ('budget', 'Budget'), ('hot', 'Hot')], max_length=20)),
                ('image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
