# Generated by Django 6.0.5 on 2026-05-28 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='providers/'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='category',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('cleaning', 'Cleaning'), ('beauty', 'Beauty Service')], max_length=50),
        ),
    ]
